# Generated by Django 3.1.6 on 2021-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_img_detect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='inputimage.png', max_length=255)),
                ('pic', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
