# Generated by Django 3.1.6 on 2021-07-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_img_detect', '0003_auto_20210706_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='name',
        ),
    ]
